version: '3'
services:
  app:
    image: golang:1.16-alpine3.13
    container_name: go
    volumes:
      - "./src:/go/src/"
    ports:
      - "80:8080"
    working_dir: /go/src/
    command: go run main.go